[package]
name = "rfetch"
version = "0.1.0"
authors = ["mWalrus <hellkvistoskar@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"
colored = "2"
